### ISSUE TITLE
Object.entries is not a function

### ISSUE THREAD

**Issue by goemaeret** [bradlc/tailwindcss-alpha#2]
Hello,

After installing and running the plugin i'm getting the following error:

`Object.entries is not a function`

Stack:
`Stack:
TypeError: Object.entries is not a function
    at /node_modules/tailwindcss-alpha/index.js:32:12`

Other plugins work fine.

My setup:

- node: 6.14.4
- npm: 3.10.10
- yarn: 1.9.4

Thanks in advance,
Thomas

**Comment by bradlc** [comment]
Hey Thomas,

Currently the plugin only works with Node.js version 7 and newer (or >=6.5 with the `--harmony` flag). Older versions don’t have `Object.entries`. Sorry about that!

When I get chance I will take a look at removing `Object.entries` to improve compatibility.

**Comment by goemaeret** [comment]
Thanks for the reply. I've upgraded node to 8.0.0 and everything works fine now.

**Comment by DeRoyace** [comment]
My node version is v10.19.0, and I'm still getting this `Object.fromEntries is not a function`

**Comment by waldekgraban** [comment]
> My node version is v10.19.0, and I'm still getting this `Object.fromEntries is not a function`

Hi, it worked for me in this configuration:
node v12.22.4 (npm v6.14.14)
