### ISSUE TITLE
Add support for Tailwindcss v1.x

### ISSUE THREAD

**Issue by hacknug** [bradlc/tailwindcss-alpha#5]
I've started migrating a personal project to v1.x and your plugin was the only thing that required an update to prevent it from breaking the build. I [forked the repo and started fixing the main issues](https://github.com/hacknug/tailwindcss-alpha/commit/6989b2f5007ec0eb54f2088972189342c1c52899) but before opening a PR, I wanted to ask for your feedback on a couple things.

Do you want future versions of the plugin to still support v0.x? If so do you think using `config()` to check if `theme` exists would be a good way to handle it?

The plugin would need to take this into account and have legacy fallbacks for `PREFIXES` and `PROPERTIES` if so.

**Comment by bradlc** [comment]
Hey @hacknug, thanks for looking at this. I think I’d like to support v0, yeah.

I guess we could do something like:

```js
alpha = config('alpha', config('theme.alpha', {})),
```

I reckon we ditch the `opacity` fallback. What do you think? Maybe even drop the option to pass values directly? Are you still allowing that in your plugins?

**Comment by hacknug** [comment]
> I reckon we ditch the `opacity` fallback.

Not sure about this since keeping it would make the plugin work without the need of adding anything else besides the plugin itself to the `plugins` array.

From a design-tokens standpoint, I feel like `opacity` and `alpha` will/should be the same 90% of the time. Maybe only when they really need to be different, `alpha` should be required?

I personally like the idea of plugins using as many common values as possible. Ideally, something like `theme.gap` would be used in [tailwindcss-gap](https://github.com/benface/tailwindcss-gap), [tailwindcss-multi-column](https://github.com/hacknug/tailwindcss-multi-column) and [tailwindcss-grid](https://github.com/chrisrowe/tailwindcss-grid).

&nbsp;

> Maybe even drop the option to pass values directly? Are you still allowing that in your plugins?

I still haven't updated any of my plugins but I think I'd like to have everything inside `theme`.

The thing is if we still need to support v0.x, can we really drop this option? Wouldn't we have to force users to change things in their projects? If so, what would be the point?

**Comment by terryupton** [comment]
Would you have a timeframe for supporting v1? 
I am starting a new project and so have I have setup the latest TW - but I do need the alpa plugin.
I use it on (probably) every project I build.

**Comment by chasegiunta** [comment]
👋 Same boat. Use this plugin on every project and anticipating it's release for supporting v1!

**Comment by terryupton** [comment]
Hey @bradlc - just a quick check-in t see if support for v1 was likely and any ETA?
I have a few projects I want to start with V1 and ideally like to keep using this.

**Comment by frontedbe** [comment]
Same here, v1 support would come in handy, thanks in advance! :)

**Comment by JSn1nj4** [comment]
Also interested in this 🙂

**Comment by terryupton** [comment]
Is there any update on this @bradlc?

**Comment by chasegiunta** [comment]
@hacknug Would you be open to releasing your fork? Maybe under a name like `tailwindcss-rgba`? I'm not confident we're going to hear back from Brad on this one, as he might have some bigger fish to fry

**Comment by hacknug** [comment]
@chasegiunta do you wanna try my PR and let me know if that works for you? I'd like to wait for @bradlc to be around so he can publish a new version of the package once we've made sure everything works correctly.

In case you don't know how to add dependencies from GitHub PRs or forks: https://martinwolf.org/2018/04/github-branch-as-dependency-package-json/

**Comment by terryupton** [comment]
@hacknug - any update on this or releasing a new package?
Unless @bradlc has any input or can merge and release a new version?

**Comment by hacknug** [comment]
My PR's been open for +2 weeks with full support for v1 (didn't mention it here since no one seems to do anything but asking for an eta). I've used it on one of my projects and everything seems to be working. 

No plans to publish it to npm since this is Brad's project and I'm pretty sure he'll get back to us _soon_. If you need it now just use my PR like I said.

**Comment by cavi21** [comment]
Hi! thanks @bradlc and @hacknug for all the work! 🙏 .... is there any idea when this PR will be merge?

Thanks a lot!

**Comment by bymayo** [comment]
Don't want to upset @bradlc but this repo isn't being updated, and someone has released alpha for background, border and text colours that works with 1.0:

https://github.com/adfdev/tailwindcss-bg-alpha

**Comment by terryupton** [comment]
The PR that @hacknug created works with 1.0 - I have used it on a project without issues. 
Hoping @bradlc could just merge the PR and then this version should be resolved.

I do use both BG and Text colours with alpha so a plugin that deals with both is preferred.

**Comment by bymayo** [comment]
@terryupton If it gets the PR merged then that's good!

**Comment by gnimmelf** [comment]
For now,
option 1, just install from `hacknug/tailwindcss-alpha`
```
npm install hacknug/tailwindcss-alpha --save-dev
```
option 2, see [comment from hackernug above](https://github.com/bradlc/tailwindcss-alpha/issues/5#issuecomment-517791410)

...until the PR comes through.
