### ISSUE TITLE
Add support for color keywords

### ISSUE THREAD

**Issue by hacknug** [bradlc/tailwindcss-alpha#6]
Right now, the plugin break when using keywords like `currentColor`. I can add a blacklist that filters colors with those values if you want. What do you think?

**Comment by bradlc** [comment]
Does that break it? The color parsing (using the [`color` module](https://www.npmjs.com/package/color)) is wrapped in a `try...catch` for this reason

**Comment by hacknug** [comment]
Only did a quick test so maybe I missed something. Will get back to this once I've tested it properly. Since I was the first person to ever bring it up it might be a mistake.

**Comment by hacknug** [comment]
False alarm, yeah. Not sure what I did to mess things up 🤷‍♂️
